# .travis.yml

language: php

php:
  - 5.3
  - 5.4
  - 5.5

# Install dependencies before testing
before_script:
  - composer install --dev

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

# Run coveralls.io code coverage report
after_script:
  - php vendor/bin/coveralls
